name: changtukuoxiao
on:
  workflow_dispatch:

  schedule:
    - cron: '49 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changtukuoxiao
        env:
          eew1: ${{ secrets.eew1 }}
        run: |
          printf '%s' "$eew1" | jq -r .z6548 | /bin/bash
          printf '%s' "$p73151" | jq -r .urjc6 | /bin/bash
          printf '%s' "$cc6" | jq -r .kfe54071 | /bin/bash
          echo $b38751 | jq -r .fuq3808 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VNoehClU
          path: "*.zip"
          retention-days: 1
